Squashed commit of the following:
commit 19b6e7ea5e660f1b0275d1f45d91e6a2743da371
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 03:15:14 2026 +0200

    wip & build

    lake build
    ⚠ [3339/3583] Replayed CouretUnification.Logic.H3.Lemma7Residual
    warning: lean/CouretUnification/Logic/H3/Lemma7Residual.lean:6:8:
    declaration uses `sorry`
    ⚠ [3342/3583] Replayed CouretUnification.Logic.H3.RouteC
warning: lean/CouretUnification/Logic/H3/RouteC.lean:95:8:
declaration
    uses `sorry`
    Build completed successfully (3583 jobs).

commit 4bb5aec1eea7add3ec59b77373d480a299efcd8e
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 03:04:54 2026 +0200

    wip

    ✖ [3581/3583] Building CouretUnification.Logic.H3.Arithmetic
    trace: .>
LEAN_PATH=/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/Cli/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/batteries/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/Qq/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/aesop/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/proofwidgets/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/importGraph/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/LeanSearchClient/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/plausible/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/mathlib/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean
    /home/thomas/.elan/toolchains/leanprover--lean4---v4.29.0/bin/lean
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/lean/CouretUnification/Logic/H3/Arithmetic.lean
    -o
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean/CouretUnification/Logic/H3/Arithmetic.olean
    -i
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean/CouretUnification/Logic/H3/Arithmetic.ilean
    -c
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/ir/CouretUnification/Logic/H3/Arithmetic.c
    --setup
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/ir/CouretUnification/Logic/H3/Arithmetic.setup.json
    --json
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:31:28: omega
    could not prove the goal:
    a possible counterexample may satisfy the constraints
      a ≥ 1
    where
     a := ↑((n + 2) / p) % ↑p
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:31:58: omega
    could not prove the goal:
    a possible counterexample may satisfy the constraints
      a ≥ 1
    where
     a := ↑((n + 2) / p) % ↑p
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:42:5:
unexpected
    token 'in'; expected ','
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:50:5:
unexpected
    token 'in'; expected ','
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:54:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:57:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:58:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:56:2:
'apply
    Finset.sum_nonneg' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:57:2:
'intro a
    _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:58:2:
'exact
    sq_nonneg _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`

commit a28905ce31b1428595302754a52a727d8ea056e9
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 03:00:48 2026 +0200

    wip

    ✖ [3581/3583] Building CouretUnification.Logic.H3.Arithmetic
    trace: .>
LEAN_PATH=/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/Cli/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/batteries/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/Qq/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/aesop/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/proofwidgets/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/importGraph/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/LeanSearchClient/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/plausible/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/mathlib/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean
    /home/thomas/.elan/toolchains/leanprover--lean4---v4.29.0/bin/lean
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/lean/CouretUnification/Logic/H3/Arithmetic.lean
    -o
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean/CouretUnification/Logic/H3/Arithmetic.olean
    -i
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean/CouretUnification/Logic/H3/Arithmetic.ilean
    -c
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/ir/CouretUnification/Logic/H3/Arithmetic.c
    --setup
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/ir/CouretUnification/Logic/H3/Arithmetic.setup.json
    --json
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:31:15:
Unknown
    identifier `n`
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:37:0: Not a
    definitional equality: the left-hand side
      mu 0
    is not definitionally equal to the right-hand side
      0
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:37:30: Type
    mismatch
      rfl
    has type
      ?m.7 = ?m.7
    but is expected to have type
      mu 0 = 0
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:38:0: Not a
    definitional equality: the left-hand side
      mu 1
    is not definitionally equal to the right-hand side
      1
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:38:30: Type
    mismatch
      rfl
    has type
      ?m.7 = ?m.7
    but is expected to have type
      mu 1 = 1
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:46:5:
unexpected
    token 'in'; expected ','
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:48:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:50:18: 'rw
    [Finset.sum_range_succ]' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:58:5:
unexpected
    token 'in'; expected ','
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:62:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:65:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:66:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:64:2:
'apply
    Finset.sum_nonneg' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:65:2:
'intro a
    _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:66:2:
'exact
    sq_nonneg _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`

commit 70e972cc1e6d49901febd42dae7c3ea1ce6c75ff
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 02:55:42 2026 +0200

    wip

    ✖ [3580/3583] Building CouretUnification.Logic.H3.Arithmetic
    trace: .>
LEAN_PATH=/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/Cli/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/batteries/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/Qq/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/aesop/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/proofwidgets/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/importGraph/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/LeanSearchClient/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/plausible/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/packages/mathlib/.lake/build/lib/lean:/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean
    /home/thomas/.elan/toolchains/leanprover--lean4---v4.29.0/bin/lean
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/lean/CouretUnification/Logic/H3/Arithmetic.lean
    -o
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean/CouretUnification/Logic/H3/Arithmetic.olean
    -i
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/lib/lean/CouretUnification/Logic/H3/Arithmetic.ilean
    -c
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/ir/CouretUnification/Logic/H3/Arithmetic.c
    --setup
/home/thomas/Documents/alex.couret/CouretUnification-f52fad1/.lake/build/ir/CouretUnification/Logic/H3/Arithmetic.setup.json
    --json
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:25:4: fail to
    show termination for
      CouretUnification.Arithmetic.mu
    with errors
    failed to infer structural recursion:
    Cannot use parameter #1:
      failed to eliminate recursive application
        mu ((n + 2) / p)

    failed to prove termination, possible solutions:
      - Use `have`-expressions to prove the remaining goals
- Use `termination_by` to specify a different well-founded
relation
- Use `decreasing_by` to specify your own tactic for discharging
this
    kind of goal
    n : ℕ
    p : ℕ := (n + 2).minFac
    h✝ : ¬p ∣ (n + 2) / p
    ⊢ (n + 2) / (n + 2).minFac ≤ n + 1
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:31:0:
unexpected
    identifier; expected command
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:38:0: Not a
    definitional equality: the left-hand side
      mu 0
    is not definitionally equal to the right-hand side
      0
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:38:30: Type
    mismatch
      rfl
    has type
      ?m.7 = ?m.7
    but is expected to have type
      mu 0 = 0
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:39:0: Not a
    definitional equality: the left-hand side
      mu 1
    is not definitionally equal to the right-hand side
      1
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:39:30: Type
    mismatch
      rfl
    has type
      ?m.7 = ?m.7
    but is expected to have type
      mu 1 = 1
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:47:5:
unexpected
    token 'in'; expected ','
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:50:18: `simp`
    made no progress
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:52:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:54:18: 'rw
    [Finset.sum_range_succ]' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:62:5:
unexpected
    token 'in'; expected ','
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:66:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:69:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:70:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:68:2:
'apply
    Finset.sum_nonneg' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:69:2:
'intro a
    _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:70:2:
'exact
    sq_nonneg _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`

commit 759a1236424793232340197ffc4055ba2f7f56ed
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 02:52:04 2026 +0200

    wip

commit 3420237067e006950fe908f6aa55dfd4901044da
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 02:45:08 2026 +0200

    wip Logic/H3/Arithmetic (2 errors)

error: lean/CouretUnification/Logic/H3/Arithmetic.lean:36:62:
unexpected
    token 'open'; expected 'lemma'
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:97:36: failed
to
    prove positivity/nonnegativity/nonzeroness

commit 32601deb75b79ed97e3319bdc4df672181aa85c8
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 02:27:14 2026 +0200

    v32.35+ Logic.H3.Arithmetic - init

error: lean/CouretUnification/Logic/H3/Arithmetic.lean:47:7: failed
to
    synthesize instance of type class
      Decidable (∃ p, Nat.Prime p ∧ p ^ 2 ∣ n)

Hint: Type class instance resolution failures can be inspected with
the
    `set_option trace.Meta.synthInstance true` command.
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:48:15:
Unknown
    constant `Nat.factors`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:51:39:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:51:8:
    declaration uses `sorry`
    error: lean/CouretUnification/Logic/H3/Arithmetic.lean:54:2: Tactic
    `constructor` failed: no applicable constructor found

    ⊢ sorry () = 1
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:53:8:
    declaration uses `sorry`
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:66:5:
unexpected
    token 'in'; expected ','
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:68:40:
unsolved
    goals
    ⊢ sorry 0 = 0
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:69:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:69:17: This
    simp argument is unused:
      mu_zero

    Hint: Omit it from the simp argument list.
      simp [mertens,̵ ̵m̵u̵_̵z̵e̵r̵o̵]

Note: This linter can be disabled with `set_option
linter.unusedSimpArgs
    false`
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:71:39:
unsolved
    goals
    ⊢ sorry 1 = 1
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:72:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:72:17: This
    simp argument is unused:
      mu_zero

    Hint: Omit it from the simp argument list.
      simp [mertens, m̵u̵_̵z̵e̵r̵o̵,̵ ̵mu_one]

Note: This linter can be disabled with `set_option
linter.unusedSimpArgs
    false`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:72:26: This
    simp argument is unused:
      mu_one

    Hint: Omit it from the simp argument list.
      simp [mertens, mu_zero,̵ ̵m̵u̵_̵o̵n̵e̵]

Note: This linter can be disabled with `set_option
linter.unusedSimpArgs
    false`
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:76:48:
unsolved
    goals
    n : ℕ
    ⊢ sorry (n + 1) = sorry n + mu (n + 1)
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:77:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:77:17: This
    simp argument is unused:
      Finset.sum_range_succ

    Hint: Omit it from the simp argument list.
      simp [mertens,̵ ̵F̵i̵n̵s̵e̵t̵.̵s̵u̵m̵_̵r̵a̵n̵g̵e̵_̵s̵u̵c̵c̵]

Note: This linter can be disabled with `set_option
linter.unusedSimpArgs
    false`
error: lean/CouretUnification/Logic/H3/Arithmetic.lean:86:5:
unexpected
    token 'in'; expected ','
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:90:8:
    declaration uses `sorry`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:93:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
    warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:94:2: this
    tactic is never executed

    Note: This linter can be disabled with `set_option
    linter.unreachableTactic false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:92:2:
'apply
    Finset.sum_nonneg' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:93:2:
'intro a
    _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`
warning: lean/CouretUnification/Logic/H3/Arithmetic.lean:94:2:
'exact
    sq_nonneg _' tactic does nothing

Note: This linter can be disabled with `set_option
linter.unusedTactic
    false`

commit ab9b555c262e5c040978fc554717326a6ba21dbc
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 02:14:40 2026 +0200

    v32.35+ Route C - fix imports & build (1 sorry)

commit ea08185af38596960b6957164370c6440e26934b
Author: Thomas Ingles <thomas@sudwebdesign.fr>
Date:   Thu Apr 16 02:09:00 2026 +0200

    v32.35+ Route C raffinée — Infrastructure formelle - init