v35.1 - CharacterLemmas - fix
error: lean/CouretUnification/Core/CharacterLemmas.lean:47:28: Unknown
constant `Finset.smul_sum`
error: lean/CouretUnification/Core/CharacterLemmas.lean:46:45: unsolved
goals
G : Type u
inst✝² : CommGroup G
inst✝¹ : Fintype G
inst✝ : DecidableEq G
c : ℂ
f : G → ℂ
⊢ c • ∑ g, f g = ∑ x, c • f x
warning: lean/CouretUnification/Core/CharacterLemmas.lean:53:4:
`push_neg` has been deprecated. Prefer using `push Not` instead.
If you'd rather continue using `push_neg` in your project, you can
implement it as follows:
```
open Lean.Parser.Tactic in
macro "push_neg" cfg:optConfig loc:(location)? : tactic =>
  `(tactic| push $cfg:optConfig Not $[$loc]?)
```