v35.1 - CharacterLemmas - fix
Unknown identifier `mul_sum` or

---

warning: lean/CouretUnification/Core/CharacterLemmas.lean:33:0:
automatically included section variable(s) unused in theorem
`CouretUnification.Core.sum_left_mul_eq_sum`:
  [DecidableEq G]
consider restructuring your `variable` declarations so that the
variables are not in scope or explicitly omit them:
  omit [DecidableEq G] in theorem ...

Note: This linter can be disabled with `set_option
linter.unusedSectionVars false`
error: lean/CouretUnification/Core/CharacterLemmas.lean:47:41: Unknown
constant `Finset.mul_sum`
error: lean/CouretUnification/Core/CharacterLemmas.lean:47:34: unsolved
goals
G : Type u
inst✝² : CommGroup G
inst✝¹ : Fintype G
inst✝ : DecidableEq G
χ : Char G
hχ : χ ≠ 1
htriv : ¬∀ (g : G), χ g = 1
a : G
ha : ¬χ a = 1
S : ℂ := ∑ g, χ g
⊢ χ a * ∑ g, χ g = ∑ g, χ a * χ g
error: lean/CouretUnification/Core/CharacterLemmas.lean:50:28: unsolved
goals
G : Type u
inst✝² : CommGroup G
inst✝¹ : Fintype G
inst✝ : DecidableEq G
χ : Char G
hχ : χ ≠ 1
htriv : ¬∀ (g : G), χ g = 1
a : G
ha : ¬χ a = 1
S : ℂ := ∑ g, χ g
⊢ ∑ x, χ a * χ x = ∑ g, χ g
warning: lean/CouretUnification/Core/CharacterLemmas.lean:51:18: This
simp argument is unused:
  S

Hint: Omit it from the simp argument list.
  simp [S̵,̵ ̵sum_left_mul_eq_sum]

Note: This linter can be disabled with `set_option linter.unusedSimpArgs
false`
warning: lean/CouretUnification/Core/CharacterLemmas.lean:51:21: This
simp argument is unused:
  sum_left_mul_eq_sum

Hint: Omit it from the simp argument list.
  simp [S,̵ ̵s̵u̵m̵_̵l̵e̵f̵t̵_̵m̵u̵l̵_̵e̵q̵_̵s̵u̵m̵]

Note: This linter can be disabled with `set_option linter.unusedSimpArgs
false`